site_name: Siddhi-gpl-execution-nlp
extra_css:
- stylesheets/extra.css
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi GPL Execution NLP: index.md
- API Docs:
  - 4.0.1-SNAPSHOT: api/4.0.1-SNAPSHOT.md
  - 4.0.2-SNAPSHOT: api/4.0.2-SNAPSHOT.md
- About:
  - License: about/license.md
theme: material
